# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "gpt-data-assistant"
client_id = "04cb1f25a07245bcb35c13a1c9e23c47"
application_url = "https://norwegian-exclude-bulletin-gore.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://norwegian-exclude-bulletin-gore.trycloudflare.com/auth/callback",
  "https://norwegian-exclude-bulletin-gore.trycloudflare.com/auth/shopify/callback",
  "https://norwegian-exclude-bulletin-gore.trycloudflare.com/api/auth/callback",
  "https://norwegian-exclude-bulletin-gore.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "data-sandbox.myshopify.com"
